# Generated by Django 3.2.15 on 2022-08-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('rc_content', models.TextField(blank=True)),
                ('rc_position', models.CharField(blank=True, max_length=255)),
                ('rc_reward', models.CharField(blank=True, max_length=255)),
                ('rc_skill', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
