# Generated by Django 3.2.15 on 2022-08-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0002_recruitment_rc_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='cp_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
