# Generated by Django 3.2.15 on 2022-08-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cp_city',
            field=models.CharField(blank=True, default=1, max_length=255),
        ),
    ]
