# Generated by Django 3.2.15 on 2022-08-18 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_company_cp_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cp_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='cp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
    ]
